nohup perl split_and_transpose_large_matrix.pl ../../../1.run_simulation/HNRNPU_merge/2.base_on_random/result1.thread1.simulation.list 100 thread1 &
nohup perl split_and_transpose_large_matrix.pl ../../../1.run_simulation/HNRNPU_merge/2.base_on_random/result1.thread2.simulation.list 100 thread2 &
nohup perl split_and_transpose_large_matrix.pl ../../../1.run_simulation/HNRNPU_merge/2.base_on_random/result1.thread3.simulation.list 100 thread3 &
nohup perl split_and_transpose_large_matrix.pl ../../../1.run_simulation/HNRNPU_merge/2.base_on_random/result1.thread4.simulation.list 100 thread4 &
nohup perl split_and_transpose_large_matrix.pl ../../../1.run_simulation/HNRNPU_merge/2.base_on_random/result1.thread5.simulation.list 100 thread5 &
nohup perl split_and_transpose_large_matrix.pl ../../../1.run_simulation/HNRNPU_merge/2.base_on_random/result1.thread6.simulation.list 100 thread6 &
nohup perl split_and_transpose_large_matrix.pl ../../../1.run_simulation/HNRNPU_merge/2.base_on_random/result1.thread7.simulation.list 100 thread7 &
nohup perl split_and_transpose_large_matrix.pl ../../../1.run_simulation/HNRNPU_merge/2.base_on_random/result1.thread8.simulation.list 100 thread8 &
nohup perl split_and_transpose_large_matrix.pl ../../../1.run_simulation/HNRNPU_merge/2.base_on_random/result1.thread9.simulation.list 100 thread9 &
nohup perl split_and_transpose_large_matrix.pl ../../../1.run_simulation/HNRNPU_merge/2.base_on_random/result1.thread10.simulation.list 100 thread10 &
nohup perl split_and_transpose_large_matrix.pl ../../../1.run_simulation/HNRNPU_merge/2.base_on_random/result1.thread11.simulation.list 100 thread11 &
nohup perl split_and_transpose_large_matrix.pl ../../../1.run_simulation/HNRNPU_merge/2.base_on_random/result1.thread12.simulation.list 100 thread12 &
nohup perl split_and_transpose_large_matrix.pl ../../../1.run_simulation/HNRNPU_merge/2.base_on_random/result1.thread13.simulation.list 100 thread13 &
nohup perl split_and_transpose_large_matrix.pl ../../../1.run_simulation/HNRNPU_merge/2.base_on_random/result1.thread14.simulation.list 100 thread14 &
nohup perl split_and_transpose_large_matrix.pl ../../../1.run_simulation/HNRNPU_merge/2.base_on_random/result1.thread15.simulation.list 100 thread15 &
nohup perl split_and_transpose_large_matrix.pl ../../../1.run_simulation/HNRNPU_merge/2.base_on_random/result1.thread16.simulation.list 100 thread16 &
nohup perl split_and_transpose_large_matrix.pl ../../../1.run_simulation/HNRNPU_merge/2.base_on_random/result1.thread17.simulation.list 100 thread17 &
nohup perl split_and_transpose_large_matrix.pl ../../../1.run_simulation/HNRNPU_merge/2.base_on_random/result1.thread18.simulation.list 100 thread18 &
nohup perl split_and_transpose_large_matrix.pl ../../../1.run_simulation/HNRNPU_merge/2.base_on_random/result1.thread19.simulation.list 100 thread19 &
nohup perl split_and_transpose_large_matrix.pl ../../../1.run_simulation/HNRNPU_merge/2.base_on_random/result1.thread20.simulation.list 100 thread20 &
