nohup perl 1.MonteCarlo_simulation.pl ../../../0.source/HNRNPU_merge/result3.HNRNPU_merge.enhancer_to_promoter.format.pair 5000 thread1 > result1.thread1.simulation.list &
nohup perl 1.MonteCarlo_simulation.pl ../../../0.source/HNRNPU_merge/result3.HNRNPU_merge.enhancer_to_promoter.format.pair 5000 thread2 > result1.thread2.simulation.list &
nohup perl 1.MonteCarlo_simulation.pl ../../../0.source/HNRNPU_merge/result3.HNRNPU_merge.enhancer_to_promoter.format.pair 5000 thread3 > result1.thread3.simulation.list &
nohup perl 1.MonteCarlo_simulation.pl ../../../0.source/HNRNPU_merge/result3.HNRNPU_merge.enhancer_to_promoter.format.pair 5000 thread4 > result1.thread4.simulation.list &
nohup perl 1.MonteCarlo_simulation.pl ../../../0.source/HNRNPU_merge/result3.HNRNPU_merge.enhancer_to_promoter.format.pair 5000 thread5 > result1.thread5.simulation.list &
nohup perl 1.MonteCarlo_simulation.pl ../../../0.source/HNRNPU_merge/result3.HNRNPU_merge.enhancer_to_promoter.format.pair 5000 thread6 > result1.thread6.simulation.list &
nohup perl 1.MonteCarlo_simulation.pl ../../../0.source/HNRNPU_merge/result3.HNRNPU_merge.enhancer_to_promoter.format.pair 5000 thread7 > result1.thread7.simulation.list &
nohup perl 1.MonteCarlo_simulation.pl ../../../0.source/HNRNPU_merge/result3.HNRNPU_merge.enhancer_to_promoter.format.pair 5000 thread8 > result1.thread8.simulation.list &
nohup perl 1.MonteCarlo_simulation.pl ../../../0.source/HNRNPU_merge/result3.HNRNPU_merge.enhancer_to_promoter.format.pair 5000 thread9 > result1.thread9.simulation.list &
nohup perl 1.MonteCarlo_simulation.pl ../../../0.source/HNRNPU_merge/result3.HNRNPU_merge.enhancer_to_promoter.format.pair 5000 thread10 > result1.thread10.simulation.list &
nohup perl 1.MonteCarlo_simulation.pl ../../../0.source/HNRNPU_merge/result3.HNRNPU_merge.enhancer_to_promoter.format.pair 5000 thread11 > result1.thread11.simulation.list &
nohup perl 1.MonteCarlo_simulation.pl ../../../0.source/HNRNPU_merge/result3.HNRNPU_merge.enhancer_to_promoter.format.pair 5000 thread12 > result1.thread12.simulation.list &
nohup perl 1.MonteCarlo_simulation.pl ../../../0.source/HNRNPU_merge/result3.HNRNPU_merge.enhancer_to_promoter.format.pair 5000 thread13 > result1.thread13.simulation.list &
nohup perl 1.MonteCarlo_simulation.pl ../../../0.source/HNRNPU_merge/result3.HNRNPU_merge.enhancer_to_promoter.format.pair 5000 thread14 > result1.thread14.simulation.list &
nohup perl 1.MonteCarlo_simulation.pl ../../../0.source/HNRNPU_merge/result3.HNRNPU_merge.enhancer_to_promoter.format.pair 5000 thread15 > result1.thread15.simulation.list &
nohup perl 1.MonteCarlo_simulation.pl ../../../0.source/HNRNPU_merge/result3.HNRNPU_merge.enhancer_to_promoter.format.pair 5000 thread16 > result1.thread16.simulation.list &
nohup perl 1.MonteCarlo_simulation.pl ../../../0.source/HNRNPU_merge/result3.HNRNPU_merge.enhancer_to_promoter.format.pair 5000 thread17 > result1.thread17.simulation.list &
nohup perl 1.MonteCarlo_simulation.pl ../../../0.source/HNRNPU_merge/result3.HNRNPU_merge.enhancer_to_promoter.format.pair 5000 thread18 > result1.thread18.simulation.list &
nohup perl 1.MonteCarlo_simulation.pl ../../../0.source/HNRNPU_merge/result3.HNRNPU_merge.enhancer_to_promoter.format.pair 5000 thread19 > result1.thread19.simulation.list &
nohup perl 1.MonteCarlo_simulation.pl ../../../0.source/HNRNPU_merge/result3.HNRNPU_merge.enhancer_to_promoter.format.pair 5000 thread20 > result1.thread20.simulation.list &
